### ISSUE TITLE
Example in README.md breaks

### ISSUE THREAD

**Issue by hanwenzhu** [davidmaamoaix/Neat#1]
I ran
```java
public class MainGame extends NeatGame {
	public static void main(String[] args) {		
		launch(args);
	}
	
	@Override
	protected void setup() {
		this.setTitle("My Game");
		this.setSize(1000, 200);
		this.setBackgroundColor("#000000");
	}
}
```
as per `README.md`. It crashes:
```
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$154(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Error: Unresolved compilation problem: 
	The type MainGame must implement the inherited abstract method NeatGame.gameStart()

	at mainGame.MainGame.gameStart(MainGame.java:4)
	at cn.davidma.neat.application.NeatGame.start(NeatGame.java:250)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application mainGame.MainGame
```

I suppose you need to implement `NeatGame.gameStart()` for the example code.

**Comment by hanwenzhu** [comment]
I only changed the `ExampleGame` class name to `MainGame` but I suppose that that doesn't matter.

**Comment by hanwenzhu** [comment]
(And shouldn't there be a blank line after class definition?)

**Comment by linxuanm** [comment]
1. Yep I forgot to override the method. That example was written in early alpha when NeatGame#gameStart is not a thing.
2. The example was copied from the Javadoc, which striped the blank line due to readability. Might change that though.

**Comment by hanwenzhu** [comment]
Closing as the bug is fixed.
